In [1]:
## Overfit and underfit
import tensorflow as tf
import os
# Vérifiez si TensorFlow détecte les GPU disponibles
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

# Affichez des informations sur les dispositifs GPU
print("CUDA_VISIBLE_DEVICES:", os.environ.get("CUDA_VISIBLE_DEVICES"))
print("LD_LIBRARY_PATH:", os.environ.get("LD_LIBRARY_PATH"))
print("PATH:", os.environ.get("PATH"))
print("CUDA_HOME:", os.environ.get("CUDA_HOME"))
print("CUDA_PATH:", os.environ.get("CUDA_PATH"))

2024-06-20 11:52:45.451902: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-20 11:52:45.451955: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-20 11:52:45.451980: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-06-20 11:52:45.459646: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


Num GPUs Available:  1
CUDA_VISIBLE_DEVICES: None
LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
PATH: /usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
CUDA_HOME: None
CUDA_PATH: None


2024-06-20 11:52:47.060173: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-06-20 11:52:47.093080: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-06-20 11:52:47.093118: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.


In [6]:
import ctypes
import os

# Définir les variables d'environnement si nécessaire
os.environ['CUDA_VISIBLE_DEVICES'] = ''  # Ou spécifiez les GPU visibles

# Recharger les bibliothèques CUDA
try:
    ctypes.CDLL('libcuda.so', mode=ctypes.RTLD_GLOBAL)
    ctypes.CDLL('libcudart.so', mode=ctypes.RTLD_GLOBAL)
    print("CUDA libraries loaded successfully")
except OSError as e:
    print("Error loading CUDA libraries:", e)

CUDA libraries loaded successfully


In [2]:
# Vérification CUDA pour TensorFlow
print("TensorFlow - CUDA disponible:", tf.test.is_built_with_cuda())
print("TensorFlow - GPU disponible:", tf.config.list_physical_devices('GPU'))
print("TensorFlow - CUDA disponible:", tf.test.is_built_with_cuda())


TensorFlow - CUDA disponible: True
TensorFlow - GPU disponible: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
TensorFlow - CUDA disponible: True


In [3]:
import tensorflow as tf

from tensorflow.keras import layers
from tensorflow.keras import regularizers

print(tf.__version__)

2.14.0


In [40]:
!pip install tensorflow-docs --no-deps
!pip install matplotlib


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python3 -m pip install --upgrade pip
  Obtaining dependency information for matplotlib from https://files.pythonhosted.org/packages/41/f1/115e7c79b4506b4f0533acba742babd9718ff92eeca6d4205843173b6173/matplotlib-3.9.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Obtaining dependency information for contourpy>=1.0.1 from https://files.pythonhosted.org/packages/ee/c0/9bd123d676eb61750e116a2cd915b06483fc406143cfc36c7f263f0f5368/contourpy-1.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Obtaining dependency information for cycler>=0.10 from https://files.pythonhosted.org/packages/e7/05/c19819d5e3d95294a6f5947fb9b9629efb316b96de511b418c53d245aae6/cycler-0.12.1-py3-none-any.whl.metadata
  Obtaining dependency information for fonttools>=4.22.0 from https://files.pythonhosted.org/packages/0a/79/b5be063ea65d048a041ad8438fa1e8c7c4bf9dc3f4ac2794a850fe70c5c5/fontto

In [41]:
import tensorflow_docs as tfdocs 
import tensorflow_docs.modeling
import tensorflow_docs.plots

In [6]:
from  IPython import display
#from matplotlib import pyplot as plt

import numpy as np

import pathlib
import shutil
import tempfile

In [45]:
import datetime
logdir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
shutil.rmtree(logdir, ignore_errors=True)


In [7]:
gz = tf.keras.utils.get_file('HIGGS.csv.gz', 'http://mlphysics.ics.uci.edu/data/higgs/HIGGS.csv.gz')


2816407858/2816407858 [==============================] - 871s 0us/step


In [10]:
FEATURES = 28


In [11]:
ds = tf.data.experimental.CsvDataset(gz,[float(),]*(FEATURES+1), compression_type="GZIP")

Row 1: (<tf.Tensor: shape=(), dtype=float32, numpy=1.0>, <tf.Tensor: shape=(), dtype=float32, numpy=0.8692932>, <tf.Tensor: shape=(), dtype=float32, numpy=-0.6350818>, <tf.Tensor: shape=(), dtype=float32, numpy=0.22569026>, <tf.Tensor: shape=(), dtype=float32, numpy=0.32747006>, <tf.Tensor: shape=(), dtype=float32, numpy=-0.6899932>, <tf.Tensor: shape=(), dtype=float32, numpy=0.75420225>, <tf.Tensor: shape=(), dtype=float32, numpy=-0.24857314>, <tf.Tensor: shape=(), dtype=float32, numpy=-1.0920639>, <tf.Tensor: shape=(), dtype=float32, numpy=0.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1.3749921>, <tf.Tensor: shape=(), dtype=float32, numpy=-0.6536742>, <tf.Tensor: shape=(), dtype=float32, numpy=0.9303491>, <tf.Tensor: shape=(), dtype=float32, numpy=1.1074361>, <tf.Tensor: shape=(), dtype=float32, numpy=1.1389043>, <tf.Tensor: shape=(), dtype=float32, numpy=-1.5781983>, <tf.Tensor: shape=(), dtype=float32, numpy=-1.0469854>, <tf.Tensor: shape=(), dtype=float32, numpy=0.0>, <tf.Tenso

2024-06-20 12:13:27.287340: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-06-20 12:13:27.287437: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-06-20 12:13:27.287462: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-06-20 12:13:28.913167: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-06-20 12:13:28.913213: I tensorflow/compile

In [12]:
def pack_row(*row):
  label = row[0]
  features = tf.stack(row[1:],1)
  label = tf.expand_dims(label, axis=1) # dans l'exo cette ligne n'existe pas et ça génére un mismatch entre la sortie (None,1) et (None,)
  return features, label

In [13]:
packed_ds = ds.batch(10000).map(pack_row).unbatch()

In [14]:
N_VALIDATION = int(1e3)
N_TRAIN = int(1e4)
BUFFER_SIZE = int(1e4)
BATCH_SIZE = 500
STEPS_PER_EPOCH = N_TRAIN//BATCH_SIZE #10000 / 500 => 20

In [15]:
validate_ds = packed_ds.take(N_VALIDATION).cache()
train_ds = packed_ds.skip(N_VALIDATION).take(N_TRAIN).cache()

In [16]:
validate_ds = validate_ds.batch(BATCH_SIZE)
train_ds = train_ds.shuffle(BUFFER_SIZE).repeat().batch(BATCH_SIZE)

In [17]:
lr_schedule = tf.keras.optimizers.schedules.InverseTimeDecay(
  0.001,
  decay_steps=STEPS_PER_EPOCH*1000,
  decay_rate=1,
  staircase=False)

def get_optimizer():
  return tf.keras.optimizers.Adam(lr_schedule)

In [42]:
def get_callbacks(name):
  return [
    tfdocs.modeling.EpochDots(),
    tf.keras.callbacks.EarlyStopping(monitor='val_binary_crossentropy', patience=200),
    tf.keras.callbacks.TensorBoard(logdir+'/'+name),
  ]

In [95]:
train_ds


<_BatchDataset element_spec=(TensorSpec(shape=(None, 28), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))>

In [96]:
validate_ds

<_BatchDataset element_spec=(TensorSpec(shape=(None, 28), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None))>

In [56]:
def compile_and_fit(model, name, optimizer=None, max_epochs=10000):
  if optimizer is None:
    optimizer = get_optimizer()
  model.compile(optimizer=optimizer,
                loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                metrics=[
                  tf.keras.metrics.BinaryCrossentropy(
                      from_logits=True, name='binary_crossentropy'),
                  'accuracy'])

  model.summary()
  print(STEPS_PER_EPOCH, max_epochs)
  history = model.fit(
    train_ds,
    steps_per_epoch = STEPS_PER_EPOCH,
    epochs=max_epochs,
    validation_data=validate_ds,
    callbacks=get_callbacks(name),
    verbose=0)
  return history

In [49]:
STEPS_PER_EPOCH

20

In [57]:
tiny_model = tf.keras.Sequential([
    layers.Dense(16, activation='elu', input_shape=(FEATURES,)),
    layers.Dense(1)
])

In [54]:
size_histories = {}


In [58]:
size_histories['Tiny'] = compile_and_fit(tiny_model, 'sizes/Tiny')


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 16)                464       
                                                                 
 dense_7 (Dense)             (None, 1)                 17        
                                                                 
Total params: 481 (1.88 KB)
Trainable params: 481 (1.88 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
20 10000

Epoch: 0, accuracy:0.4807,  binary_crossentropy:0.7830,  loss:0.7830,  val_accuracy:0.4670,  val_binary_crossentropy:0.7618,  val_loss:0.7618,  
..

2024-06-20 12:23:55.122691: I tensorflow/core/framework/local_rendezvous.cc:421] Local rendezvous recv item cancelled. Key hash: 4820092430375305599
2024-06-20 12:23:55.122761: I tensorflow/core/framework/local_rendezvous.cc:421] Local rendezvous recv item cancelled. Key hash: 1052680143665384865
2024-06-20 12:23:55.122797: I tensorflow/core/framework/local_rendezvous.cc:421] Local rendezvous recv item cancelled. Key hash: 10628074834390090960


..................................................................................................
Epoch: 100, accuracy:0.6011,  binary_crossentropy:0.6252,  loss:0.6252,  val_accuracy:0.5600,  val_binary_crossentropy:0.6264,  val_loss:0.6264,  
....................................................................................................
Epoch: 200, accuracy:0.6238,  binary_crossentropy:0.6117,  loss:0.6117,  val_accuracy:0.6030,  val_binary_crossentropy:0.6109,  val_loss:0.6109,  
....................................................................................................
Epoch: 300, accuracy:0.6472,  binary_crossentropy:0.6002,  loss:0.6002,  val_accuracy:0.6170,  val_binary_crossentropy:0.6026,  val_loss:0.6026,  
....................................................................................................
Epoch: 400, accuracy:0.6594,  binary_crossentropy:0.5910,  loss:0.5910,  val_accuracy:0.6260,  val_binary_crossentropy:0.5968,  val_loss:0.5968,  
..........

In [60]:
medium_model = tf.keras.Sequential([
    layers.Dense(64, activation='elu', input_shape=(FEATURES,)),
    layers.Dense(64, activation='elu'),
    layers.Dense(64, activation='elu'),
    layers.Dense(1)
])

In [61]:
size_histories['Medium']  = compile_and_fit(medium_model, "sizes/Medium")


Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             (None, 64)                1856      
                                                                 
 dense_9 (Dense)             (None, 64)                4160      
                                                                 
 dense_10 (Dense)            (None, 64)                4160      
                                                                 
 dense_11 (Dense)            (None, 1)                 65        
                                                                 
Total params: 10241 (40.00 KB)
Trainable params: 10241 (40.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
20 10000

Epoch: 0, accuracy:0.4873,  binary_crossentropy:0.6944,  loss:0.6944,  val_accuracy:0.4640,  val_binary_crossentropy:0.6836,  val_loss:0.683

2024-06-20 13:16:19.378650: I tensorflow/core/framework/local_rendezvous.cc:421] Local rendezvous recv item cancelled. Key hash: 16022069897694337571
2024-06-20 13:16:19.378928: I tensorflow/core/framework/local_rendezvous.cc:421] Local rendezvous recv item cancelled. Key hash: 10608423756708943253
2024-06-20 13:16:19.378963: I tensorflow/core/framework/local_rendezvous.cc:421] Local rendezvous recv item cancelled. Key hash: 690498525601109573


...................................................................................................
Epoch: 100, accuracy:0.7172,  binary_crossentropy:0.5305,  loss:0.5305,  val_accuracy:0.6680,  val_binary_crossentropy:0.6020,  val_loss:0.6020,  
....................................................................................................
Epoch: 200, accuracy:0.7802,  binary_crossentropy:0.4352,  loss:0.4352,  val_accuracy:0.6430,  val_binary_crossentropy:0.6982,  val_loss:0.6982,  
.............................................................

In [62]:
large_model = tf.keras.Sequential([
    layers.Dense(512, activation='elu', input_shape=(FEATURES,)),
    layers.Dense(512, activation='elu'),
    layers.Dense(512, activation='elu'),
    layers.Dense(512, activation='elu'),
    layers.Dense(1)
])

In [63]:
size_histories['large'] = compile_and_fit(large_model, "sizes/large")


Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 512)               14848     
                                                                 
 dense_13 (Dense)            (None, 512)               262656    
                                                                 
 dense_14 (Dense)            (None, 512)               262656    
                                                                 
 dense_15 (Dense)            (None, 512)               262656    
                                                                 
 dense_16 (Dense)            (None, 1)                 513       
                                                                 
Total params: 803329 (3.06 MB)
Trainable params: 803329 (3.06 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
20 10000

Epoch: 0

2024-06-20 13:24:45.689750: I tensorflow/core/framework/local_rendezvous.cc:421] Local rendezvous recv item cancelled. Key hash: 6826301605450314379
2024-06-20 13:24:45.689864: I tensorflow/core/framework/local_rendezvous.cc:421] Local rendezvous recv item cancelled. Key hash: 6041199798840450329
2024-06-20 13:24:45.689932: I tensorflow/core/framework/local_rendezvous.cc:421] Local rendezvous recv item cancelled. Key hash: 4141405783816510582


...................................................................................................
Epoch: 100, accuracy:1.0000,  binary_crossentropy:0.0025,  loss:0.0025,  val_accuracy:0.6490,  val_binary_crossentropy:1.7604,  val_loss:1.7604,  
....................................................................................................
Epoch: 200, accuracy:1.0000,  binary_crossentropy:0.0001,  loss:0.0001,  val_accuracy:0.6540,  val_binary_crossentropy:2.4324,  val_loss:2.4324,  
........................

In [65]:
regularizer_histories = {}
regularizer_histories['Tiny'] = size_histories['Tiny']

In [66]:
l2_model = tf.keras.Sequential([
    layers.Dense(512, activation='elu',
                 kernel_regularizer=regularizers.l2(0.001),
                 input_shape=(FEATURES,)),
    layers.Dense(512, activation='elu',
                 kernel_regularizer=regularizers.l2(0.001)),
    layers.Dense(512, activation='elu',
                 kernel_regularizer=regularizers.l2(0.001)),
    layers.Dense(512, activation='elu',
                 kernel_regularizer=regularizers.l2(0.001)),
    layers.Dense(1)
])

regularizer_histories['l2'] = compile_and_fit(l2_model, "regularizers/l2")

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_22 (Dense)            (None, 512)               14848     
                                                                 
 dense_23 (Dense)            (None, 512)               262656    
                                                                 
 dense_24 (Dense)            (None, 512)               262656    
                                                                 
 dense_25 (Dense)            (None, 512)               262656    
                                                                 
 dense_26 (Dense)            (None, 1)                 513       
                                                                 
Total params: 803329 (3.06 MB)
Trainable params: 803329 (3.06 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
20 10000

Epoch: 0

2024-06-20 14:07:20.725514: I tensorflow/core/framework/local_rendezvous.cc:421] Local rendezvous recv item cancelled. Key hash: 9311333154006756914


...................................................................................................
Epoch: 100, accuracy:0.6527,  binary_crossentropy:0.5953,  loss:0.6177,  val_accuracy:0.6510,  val_binary_crossentropy:0.5858,  val_loss:0.6084,  
....................................................................................................
Epoch: 200, accuracy:0.6623,  binary_crossentropy:0.5918,  loss:0.6134,  val_accuracy:0.6410,  val_binary_crossentropy:0.5884,  val_loss:0.6102,  
....................................................................................................
Epoch: 300, accuracy:0.6781,  binary_crossentropy:0.5755,  loss:0.5961,  val_accuracy:0.7070,  val_binary_crossentropy:0.5835,  val_loss:0.6041,  
.........................................................

In [67]:
dropout_model = tf.keras.Sequential([
    layers.Dense(512, activation='elu', input_shape=(FEATURES,)),
    layers.Dropout(0.5),
    layers.Dense(512, activation='elu'),
    layers.Dropout(0.5),
    layers.Dense(512, activation='elu'),
    layers.Dropout(0.5),
    layers.Dense(512, activation='elu'),
    layers.Dropout(0.5),
    layers.Dense(1)
])

regularizer_histories['dropout'] = compile_and_fit(dropout_model, "regularizers/dropout")

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_27 (Dense)            (None, 512)               14848     
                                                                 
 dropout (Dropout)           (None, 512)               0         
                                                                 
 dense_28 (Dense)            (None, 512)               262656    
                                                                 
 dropout_1 (Dropout)         (None, 512)               0         
                                                                 
 dense_29 (Dense)            (None, 512)               262656    
                                                                 
 dropout_2 (Dropout)         (None, 512)               0         
                                                                 
 dense_30 (Dense)            (None, 512)              

2024-06-20 14:25:34.447088: I tensorflow/core/framework/local_rendezvous.cc:421] Local rendezvous recv item cancelled. Key hash: 6826301605450314379
2024-06-20 14:25:34.447163: I tensorflow/core/framework/local_rendezvous.cc:421] Local rendezvous recv item cancelled. Key hash: 4141405783816510582


...................................................................................................
Epoch: 100, accuracy:0.6587,  binary_crossentropy:0.5967,  loss:0.5967,  val_accuracy:0.6730,  val_binary_crossentropy:0.5821,  val_loss:0.5821,  
....................................................................................................
Epoch: 200, accuracy:0.6888,  binary_crossentropy:0.5518,  loss:0.5518,  val_accuracy:0.6800,  val_binary_crossentropy:0.5823,  val_loss:0.5823,  
....................................................................................................
Epoch: 300, accuracy:0.7204,  binary_crossentropy:0.5141,  loss:0.5141,  val_accuracy:0.6750,  val_binary_crossentropy:0.6195,  val_loss:0.6195,  
....................

In [68]:
combined_model = tf.keras.Sequential([
    layers.Dense(512, kernel_regularizer=regularizers.l2(0.0001),
                 activation='elu', input_shape=(FEATURES,)),
    layers.Dropout(0.5),
    layers.Dense(512, kernel_regularizer=regularizers.l2(0.0001),
                 activation='elu'),
    layers.Dropout(0.5),
    layers.Dense(512, kernel_regularizer=regularizers.l2(0.0001),
                 activation='elu'),
    layers.Dropout(0.5),
    layers.Dense(512, kernel_regularizer=regularizers.l2(0.0001),
                 activation='elu'),
    layers.Dropout(0.5),
    layers.Dense(1)
])

regularizer_histories['combined'] = compile_and_fit(combined_model, "regularizers/combined")

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_32 (Dense)            (None, 512)               14848     
                                                                 
 dropout_4 (Dropout)         (None, 512)               0         
                                                                 
 dense_33 (Dense)            (None, 512)               262656    
                                                                 
 dropout_5 (Dropout)         (None, 512)               0         
                                                                 
 dense_34 (Dense)            (None, 512)               262656    
                                                                 
 dropout_6 (Dropout)         (None, 512)               0         
                                                                 
 dense_35 (Dense)            (None, 512)              

2024-06-20 14:27:39.231074: I tensorflow/core/framework/local_rendezvous.cc:421] Local rendezvous recv item cancelled. Key hash: 6218956072787107339
2024-06-20 14:27:39.231126: I tensorflow/core/framework/local_rendezvous.cc:421] Local rendezvous recv item cancelled. Key hash: 9311333154006756914


...................................................................................................
Epoch: 100, accuracy:0.6465,  binary_crossentropy:0.6049,  loss:0.6352,  val_accuracy:0.6590,  val_binary_crossentropy:0.5864,  val_loss:0.6165,  
....................................................................................................
Epoch: 200, accuracy:0.6644,  binary_crossentropy:0.5914,  loss:0.6166,  val_accuracy:0.6710,  val_binary_crossentropy:0.5687,  val_loss:0.5939,  
....................................................................................................
Epoch: 300, accuracy:0.6703,  binary_crossentropy:0.5812,  loss:0.6089,  val_accuracy:0.6950,  val_binary_crossentropy:0.5625,  val_loss:0.5902,  
....................................................................................................
Epoch: 400, accuracy:0.6749,  binary_crossentropy:0.5764,  loss:0.6063,  val_accuracy:0.6790,  val_binary_crossentropy:0.5577,  val_loss:0.5875,  
.........